name: Build and Deploy to /docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build with Vite
      run: npm run build

    - name: Deploy to /docs
      run: |
        rm -rf docs
        mv dist docs
    - name: Commit and push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Deploy built site [skip ci]"
          git push
        fi
