name: Build + Optimize + Deploy 3D Viewer

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Optimize models
      run: |
        mkdir -p public/models_optimized
        for f in public/models/*.glb; do
          basename=$(basename "$f")
          echo "Optimizing: $basename"
          ./tools/gltfpack -i "$f" -o "public/models_optimized/$basename" -cc
        done

    - name: Build with Vite
      run: npm run build

    - name: Deploy to /docs
      run: |
        rm -rf docs
        mv dist docs

    - name: Commit and push
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs public/models_optimized
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Deploy built site with optimized models [skip ci]"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
        fi
